Hisobot yaratishda xato: unsupported operand type(s) for +: 'int' and 'str'
Hisobot yaratishda xato: 'Meal' object has no attribute 'calculate_possible_portions'
Hisobot 2025-05 yaratildi.
Hisobot yaratishda xato: UNIQUE constraint failed: reports_monthlyreport.month
Hisobot 2025-05 yangilandi.
Hisobot 2025-05 yaratildi.
Hisobot 2025-05 yaratildi.
Hisobot 2025-05 uchun boshlandi.
Tayyorlangan porsiyalar: 0, Tarqatishlar soni: 0
2025-05 uchun MealDistribution ma'lumotlari yo‘q.
Mumkin bo‘lgan porsiyalar: 0
Hisobot 2025-05 yaratildi. Ma'lumotlar: prepared=0, possible=0, percent=0, warning=False
Hisobot 2025-01 uchun boshlandi.
Tayyorlangan porsiyalar: 0, Tarqatishlar soni: 0
2025-01 uchun MealDistribution ma'lumotlari yo‘q.
Mumkin bo‘lgan porsiyalar: 0
Hisobot 2025-01 yaratildi. Ma'lumotlar: prepared=0, possible=0, percent=0, warning=False
Hisobot 2024-02 uchun boshlandi.
Tayyorlangan porsiyalar: 0, Tarqatishlar soni: 0
2024-02 uchun MealDistribution ma'lumotlari yo‘q.
Mumkin bo‘lgan porsiyalar: 0
Hisobot 2024-02 yaratildi. Ma'lumotlar: prepared=0, possible=0, percent=0, warning=False
Hisobot 2025-02 uchun boshlandi.
Tayyorlangan porsiyalar: 0, Tarqatishlar soni: 0
2025-02 uchun MealDistribution ma'lumotlari yo‘q.
Mumkin bo‘lgan porsiyalar: 0
Hisobot 2025-02 yaratildi. Ma'lumotlar: prepared=0, possible=0, percent=0, warning=False
Hisobot 2025-02 uchun boshlandi.
Tayyorlangan porsiyalar: 0, Tarqatishlar soni: 0
2025-02 uchun MealDistribution ma'lumotlari yo‘q.
Mumkin bo‘lgan porsiyalar: 0
Hisobot 2025-02 yangilandi. Ma'lumotlar: prepared=0, possible=0, percent=0.0, warning=False
Hisobot 2005-10 uchun boshlandi.
Tayyorlangan porsiyalar: 0, Tarqatishlar soni: 0
2005-10 uchun MealDistribution ma'lumotlari yo‘q.
Mumkin bo‘lgan porsiyalar: 0
Hisobot 2005-10 yaratildi. Ma'lumotlar: prepared=0, possible=0, percent=0, warning=False
Starting report generation for 2025-05
Found 1 distributions: [{'id': 1, 'meal_id': 16, 'quantity': 10, 'date_time': datetime.datetime(2025, 5, 15, 7, 0, tzinfo=datetime.timezone.utc)}]
Prepared portions: 10
Processing meal 16 - Barak
Meal 16 possible portions: 0, quantity: 10
Meal 16 has invalid possible portions: 0
Total possible portions: 0
Report 20 created/updated: prepared=10, possible=0
Starting report generation for 2025-05
Found 1 distributions: [{'id': 1, 'meal_id': 16, 'quantity': 10, 'date_time': datetime.datetime(2025, 5, 15, 7, 0, tzinfo=datetime.timezone.utc)}]
Prepared portions: 10
Processing meal 16 - Barak
Meal 16 possible portions: 0, quantity: 10
Meal 16 has invalid possible portions: 0
Total possible portions: 0
Report 20 created/updated: prepared=10, possible=0
Starting report for 2024-10
Found 0 distributions: []
Prepared portions: 0
No distributions found
Total possible portions: 0
Report 18 updated: prepared=0, possible=0
Generating report for 2025-05
Input data: prepared=10, possible=20, percent=10.0, warning=True
Report 20 updated: prepared=10, possible=20, percent=10.0, warning=True
Generating report for 2025-01
Input data: prepared=10, possible=20, percent=10.0, warning=False
Report 21 created: prepared=10, possible=20, percent=10.0, warning=False
Generating report for 2025-05
Input data: prepared=2, possible=7, percent=20.0, warning=True
Report 22 created: prepared=2, possible=7, percent=20.0, warning=True
Generating report for 2025-05
Input data: prepared=10, possible=50, percent=20.0, warning=True
Report 22 updated: prepared=10, possible=50, percent=20.0, warning=True
Generating report for 2025-05
Input data: prepared=10, possible=20, percent=30.0, warning=True
Report 23 created: prepared=10, possible=20, percent=30.0, warning=True
Generating report for 2025-04
Input data: prepared=10, possible=30, percent=20.0, warning=True
Report 24 created: prepared=10, possible=30, percent=20.0, warning=True
Generating report for 2024-04
Input data: prepared=10, possible=20, percent=20.0, warning=True
Error generating report for 2024-04: no such column: reports_monthlyreport.year
Traceback (most recent call last):
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: reports_monthlyreport.year

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\reports\tasks.py", line 13, in generate_monthly_report
    report, created = MonthlyReport.objects.update_or_create(
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year=year,
        ^^^^^^^^^^
    ...<6 lines>...
        }
        ^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 988, in update_or_create
    obj, created = self.select_for_update().get_or_create(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        create_defaults, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 946, in get_or_create
    return self.get(**kwargs), False
           ~~~~~~~~^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: reports_monthlyreport.year
Generating report for 2024-04
Input data: prepared=10, possible=20, percent=20.0, warning=True
Error generating report for 2024-04: no such column: reports_monthlyreport.year
Traceback (most recent call last):
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: reports_monthlyreport.year

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\reports\tasks.py", line 13, in generate_monthly_report
    report, created = MonthlyReport.objects.update_or_create(
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year=year,
        ^^^^^^^^^^
    ...<6 lines>...
        }
        ^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 988, in update_or_create
    obj, created = self.select_for_update().get_or_create(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        create_defaults, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 946, in get_or_create
    return self.get(**kwargs), False
           ~~~~~~~~^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: reports_monthlyreport.year
Generating report for 2024-04
Input data: prepared=10, possible=20, percent=20.0, warning=True
Error generating report for 2024-04: Cannot resolve keyword 'month' into field. Choices are: created_at, difference_percent, id, possible_portions, prepared_portions, report_date, updated_at, warning
Traceback (most recent call last):
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\reports\tasks.py", line 13, in generate_monthly_report
    report, created = MonthlyReport.objects.update_or_create(
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year=year,
        ^^^^^^^^^^
    ...<6 lines>...
        }
        ^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 988, in update_or_create
    obj, created = self.select_for_update().get_or_create(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        create_defaults, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 946, in get_or_create
    return self.get(**kwargs), False
           ~~~~~~~~^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 619, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 1491, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 1509, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 1516, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'month' into field. Choices are: created_at, difference_percent, id, possible_portions, prepared_portions, report_date, updated_at, warning
Generating report for 2024-04
Input data: prepared=10, possible=20, percent=20.0, warning=True
Error generating report for 2024-04: Cannot resolve keyword 'month' into field. Choices are: created_at, difference_percent, id, possible_portions, prepared_portions, report_date, updated_at, warning
Traceback (most recent call last):
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\reports\tasks.py", line 13, in generate_monthly_report
    report, created = MonthlyReport.objects.update_or_create(
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year=year,
        ^^^^^^^^^^
    ...<6 lines>...
        }
        ^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 988, in update_or_create
    obj, created = self.select_for_update().get_or_create(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        create_defaults, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 946, in get_or_create
    return self.get(**kwargs), False
           ~~~~~~~~^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 619, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 1491, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 1509, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\query.py", line 1516, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PDP University\2 - Kurs\2 semester\Essayment\Programming\Task\Code\kindergarten_org\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'month' into field. Choices are: created_at, difference_percent, id, possible_portions, prepared_portions, report_date, updated_at, warning
Generating report for 2025-05
Input data: prepared=10, possible=20, percent=20.0, warning=False
Report 1 created: prepared=10, possible=20, percent=20.0, warning=False
Generating report for 2025-01
Input data: prepared=10, possible=20, percent=20.0, warning=True
Report 2 created: prepared=10, possible=20, percent=20.0, warning=True
Generating report for 2025-02
Input data: prepared=10, possible=20, percent=20.0, warning=True
Report 3 created: prepared=10, possible=20, percent=20.0, warning=True
Generating report for 2024-09
Input data: prepared=10, possible=20, percent=20.0, warning=True
Report 4 created: prepared=10, possible=20, percent=20.0, warning=True
Generating report for 2024-11
Input data: prepared=40, possible=100, percent=20.0, warning=True
Report 5 created: prepared=40, possible=100, percent=20.0, warning=True
Generating report for 2025-05
Input data: prepared=50, possible=100, percent=50.0, warning=True
Report 6 created: prepared=50, possible=100, percent=50.0, warning=True
Generating report for 2025-05
Input data: prepared=50, possible=100, percent=50.0, warning=True
Report 6 updated: prepared=50, possible=100, percent=50.0, warning=True
Generating report for 2025-05
Input data: prepared=10, possible=20, percent=40.0, warning=True
Report 6 updated: prepared=10, possible=20, percent=40.0, warning=True
